//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team75
{
    public partial class AccidentalLeaveSubmission
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblEmployeeID;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.GridView gvAccidentalLeaves;

        protected global::System.Web.UI.WebControls.Button btnBack;
    }
}
