//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team75
{
    public partial class ApplyAccidentalLeave
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblEmployeeID;

        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        protected global::System.Web.UI.WebControls.Button btnSubmit;

        protected global::System.Web.UI.WebControls.Button btnHome;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
